File Rouge/Site/Regnaloub/src/Entity/ConsoleGaming.php
<?php

namespace App\Entity;

use App\Repository\ConsoleGamingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ConsoleGamingRepository::class)]
class ConsoleGaming
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $lib_asso = null;

    #[ORM\Column]
    private ?int $port_usb = null;

    #[ORM\Column]
    private ?int $port_hdmi = null;

    #[ORM\Column]
    private ?int $disque_dur = null;

    #[ORM\Column(length: 50)]
    private ?string $resolution = null;

    #[ORM\Column]
    private ?int $fps = null;

    #[ORM\OneToMany(mappedBy: 'consoleGaming', targetEntity: Produit::class)]
    private Collection $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->lib_asso;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibAsso(): ?string
    {
        return $this->lib_asso;
    }

    public function setLibAsso(string $lib_asso): static
    {
        $this->lib_asso = $lib_asso;

        return $this;
    }

    public function getPortUsb(): ?int
    {
        return $this->port_usb;
    }

    public function setPortUsb(int $port_usb): static
    {
        $this->port_usb = $port_usb;

        return $this;
    }

    public function getPortHdmi(): ?int
    {
        return $this->port_hdmi;
    }

    public function setPortHdmi(int $port_hdmi): static
    {
        $this->port_hdmi = $port_hdmi;

        return $this;
    }

    public function getDisqueDur(): ?int
    {
        return $this->disque_dur;
    }

    public function setDisqueDur(int $disque_dur): static
    {
        $this->disque_dur = $disque_dur;

        return $this;
    }

    public function getResolution(): ?string
    {
        return $this->resolution;
    }

    public function setResolution(string $resolution): static
    {
        $this->resolution = $resolution;

        return $this;
    }

    public function getFps(): ?int
    {
        return $this->fps;
    }

    public function setFps(int $fps): static
    {
        $this->fps = $fps;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setConsoleGaming($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getConsoleGaming() === $this) {
                $produit->setConsoleGaming(null);
            }
        }

        return $this;
    }
}

File Rouge/Site/Regnaloub/src/Entity/Imprimante.php
<?php

namespace App\Entity;

use App\Repository\ImprimanteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ImprimanteRepository::class)]
class Imprimante
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $lib_asso = null;

    #[ORM\Column(length: 50)]
    private ?string $type = null;

    #[ORM\Column(length: 50)]
    private ?string $vit = null;

    #[ORM\Column(length: 50)]
    private ?string $qualiter = null;

    #[ORM\Column(length: 50)]
    private ?string $qualiter_photo = null;

    #[ORM\Column(length: 40)]
    private ?string $format = null;

    #[ORM\OneToMany(mappedBy: 'Imprimante', targetEntity: Produit::class)]
    private Collection $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->lib_asso;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibAsso(): ?string
    {
        return $this->lib_asso;
    }

    public function setLibAsso(string $lib_asso): static
    {
        $this->lib_asso = $lib_asso;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getVit(): ?string
    {
        return $this->vit;
    }

    public function setVit(string $vit): static
    {
        $this->vit = $vit;

        return $this;
    }

    public function getQualiter(): ?string
    {
        return $this->qualiter;
    }

    public function setQualiter(string $qualiter): static
    {
        $this->qualiter = $qualiter;

        return $this;
    }

    public function getQualiterPhoto(): ?string
    {
        return $this->qualiter_photo;
    }

    public function setQualiterPhoto(string $qualiter_photo): static
    {
        $this->qualiter_photo = $qualiter_photo;

        return $this;
    }

    public function getFormat(): ?string
    {
        return $this->format;
    }

    public function setFormat(string $format): static
    {
        $this->format = $format;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setImprimante($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getImprimante() === $this) {
                $produit->setImprimante(null);
            }
        }

        return $this;
    }
}

File Rouge/Site/Regnaloub/src/Entity/Television.php
<?php

namespace App\Entity;

use App\Repository\TelevisionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TelevisionRepository::class)]
class Television
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $lib_asso = null;

    #[ORM\Column(length: 50)]
    private ?string $resolution = null;

    #[ORM\Column(length: 10)]
    private ?string $def = null;

    #[ORM\Column(length: 50)]
    private ?string $techno = null;

    #[ORM\Column(length: 50)]
    private ?string $proc = null;

    #[ORM\Column(length: 10)]
    private ?string $son_puiss = null;

    #[ORM\Column]
    private ?int $port_hdmi = null;

    #[ORM\Column]
    private ?int $port_usb = null;

    #[ORM\OneToMany(mappedBy: 'Television', targetEntity: Produit::class)]
    private Collection $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->lib_asso;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibAsso(): ?string
    {
        return $this->lib_asso;
    }

    public function setLibAsso(string $lib_asso): static
    {
        $this->lib_asso = $lib_asso;

        return $this;
    }

    public function getResolution(): ?string
    {
        return $this->resolution;
    }

    public function setResolution(string $resolution): static
    {
        $this->resolution = $resolution;

        return $this;
    }

    public function getDef(): ?string
    {
        return $this->def;
    }

    public function setDef(string $def): static
    {
        $this->def = $def;

        return $this;
    }

    public function getTechno(): ?string
    {
        return $this->techno;
    }

    public function setTechno(string $techno): static
    {
        $this->techno = $techno;

        return $this;
    }

    public function getProc(): ?string
    {
        return $this->proc;
    }

    public function setProc(string $proc): static
    {
        $this->proc = $proc;

        return $this;
    }

    public function getSonPuiss(): ?string
    {
        return $this->son_puiss;
    }

    public function setSonPuiss(string $son_puiss): static
    {
        $this->son_puiss = $son_puiss;

        return $this;
    }

    public function getPortHdmi(): ?int
    {
        return $this->port_hdmi;
    }

    public function setPortHdmi(int $port_hdmi): static
    {
        $this->port_hdmi = $port_hdmi;

        return $this;
    }

    public function getPortUsb(): ?int
    {
        return $this->port_usb;
    }

    public function setPortUsb(int $port_usb): static
    {
        $this->port_usb = $port_usb;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setTelevision($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getTelevision() === $this) {
                $produit->setTelevision(null);
            }
        }

        return $this;
    }
}

File Rouge/Site/Regnaloub/src/Entity/UniteCentral.php
<?php

namespace App\Entity;

use App\Repository\UniteCentralRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UniteCentralRepository::class)]
class UniteCentral
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $lib_asso = null;

    #[ORM\Column(length: 50)]
    private ?string $proc = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 4, scale: 2)]
    private ?string $proc_freq = null;

    #[ORM\Column]
    private ?int $proc_nbr_coeur = null;

    #[ORM\Column]
    private ?int $ram = null;

    #[ORM\Column(length: 20)]
    private ?string $ram_type = null;

    #[ORM\Column(length: 50)]
    private ?string $cg_modele = null;

    #[ORM\Column]
    private ?int $stkage = null;

    #[ORM\Column(length: 20)]
    private ?string $type_stkage = null;

    #[ORM\Column(length: 10)]
    private ?string $wifi = null;

    #[ORM\Column]
    private ?int $port_usb = null;

    #[ORM\Column]
    private ?int $port_hdmi = null;

    #[ORM\Column(length: 20)]
    private ?string $sys_exp = null;

    #[ORM\OneToMany(mappedBy: 'UniteCentral', targetEntity: Produit::class)]
    private Collection $produits;

    public function __construct()
    {
        $this->produits = new ArrayCollection();
    }

    public function __toString()
    {
        return $this->lib_asso;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibAsso(): ?string
    {
        return $this->lib_asso;
    }

    public function setLibAsso(string $lib_asso): static
    {
        $this->lib_asso = $lib_asso;

        return $this;
    }

    public function getProc(): ?string
    {
        return $this->proc;
    }

    public function setProc(string $proc): static
    {
        $this->proc = $proc;

        return $this;
    }

    public function getProcFreq(): ?string
    {
        return $this->proc_freq;
    }

    public function setProcFreq(string $proc_freq): static
    {
        $this->proc_freq = $proc_freq;

        return $this;
    }

    public function getProcNbrCoeur(): ?int
    {
        return $this->proc_nbr_coeur;
    }

    public function setProcNbrCoeur(int $proc_nbr_coeur): static
    {
        $this->proc_nbr_coeur = $proc_nbr_coeur;

        return $this;
    }

    public function getRam(): ?int
    {
        return $this->ram;
    }

    public function setRam(int $ram): static
    {
        $this->ram = $ram;

        return $this;
    }

    public function getRamType(): ?string
    {
        return $this->ram_type;
    }

    public function setRamType(string $ram_type): static
    {
        $this->ram_type = $ram_type;

        return $this;
    }

    public function getCgModele(): ?string
    {
        return $this->cg_modele;
    }

    public function setCgModele(string $cg_modele): static
    {
        $this->cg_modele = $cg_modele;

        return $this;
    }

    public function getStkage(): ?int
    {
        return $this->stkage;
    }

    public function setStkage(int $stkage): static
    {
        $this->stkage = $stkage;

        return $this;
    }

    public function getTypeStkage(): ?string
    {
        return $this->type_stkage;
    }

    public function setTypeStkage(string $type_stkage): static
    {
        $this->type_stkage = $type_stkage;

        return $this;
    }

    public function getWifi(): ?string
    {
        return $this->wifi;
    }

    public function setWifi(string $wifi): static
    {
        $this->wifi = $wifi;

        return $this;
    }

    public function getPortUsb(): ?int
    {
        return $this->port_usb;
    }

    public function setPortUsb(int $port_usb): static
    {
        $this->port_usb = $port_usb;

        return $this;
    }

    public function getPortHdmi(): ?int
    {
        return $this->port_hdmi;
    }

    public function setPortHdmi(int $port_hdmi): static
    {
        $this->port_hdmi = $port_hdmi;

        return $this;
    }

    public function getSysExp(): ?string
    {
        return $this->sys_exp;
    }

    public function setSysExp(string $sys_exp): static
    {
        $this->sys_exp = $sys_exp;

        return $this;
    }

    /**
     * @return Collection<int, Produit>
     */
    public function getProduits(): Collection
    {
        return $this->produits;
    }

    public function addProduit(Produit $produit): static
    {
        if (!$this->produits->contains($produit)) {
            $this->produits->add($produit);
            $produit->setUniteCentral($this);
        }

        return $this;
    }

    public function removeProduit(Produit $produit): static
    {
        if ($this->produits->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getUniteCentral() === $this) {
                $produit->setUniteCentral(null);
            }
        }

        return $this;
    }
}

File Rouge/Site/Regnaloub/templates/produit_detail/base_detail_produit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Detail Produit{% endblock %}

{% block pub %} {% endblock %}

{% block body %}
    {{ categorie.lib }}
    {% block caractéristique %}

    {% endblock %}

{% endblock %}

File Rouge/Site/Regnaloub/templates/produit_detail/console_gaming.html.twig
{% extends 'base_detail_produit.html.twig' %}

{% block caractéristique %}
    {% for produit in produit %}
        {% for detailProduit in detailProduit %}
            <div class="caracteristique_produit">
                <h2>Caractéristique du produit</h2>
                <h3>Caractéristiques générales</h3>
                    <p>Marque: {{ produit.marque }}</p>
                    <p>Modèle: {{ produit.modele }}</p>
                    <p>Stockage: {{ detailProduit.disqueDur }}Go</p>
                    <p>Couleur: {{ produit.couleur }}</p>
                <h3>Ecran</h3>
                    <p>Résolution de l'ecran: {{ detailProduit.resolution }} pixels</p>
                    <p>Nombre de FPS: {{ detailProduit.fps }} FPS</p>
                <h3>Connectique</h3>
                    <p>Nombre de port USB: {{ detailProduit.portUsb }}</p>
                    <p>Nombre de port HDMI: {{ detailProduit.portHdmi }}</p>
                <h3>Dimension</h3>
                    <p>Hauteur: {{ produit.hauteur }} cm</p>
                    <p>Largeur: {{ produit.largeur }} cm</p>
                    <p>Profondeur: {{ produit.profondeur }} cm</p>
                    <p>Poid: {{ produit.poid }} g</p>
            </div>
            {% endfor %}
    {% endfor %}
{% endblock %}

File Rouge/Site/Regnaloub/templates/produit_detail/enceinte.html.twig
{% extends 'base_detail_produit.html.twig' %}

{% block caractéristique %}
    {% for produit in produit %}
        {% for detailProduit in detailProduit %}
            <div class="caracteristique_produit">
                <h2>Caractéristique du produit</h2>
                <h3>Caractéristiques générales</h3>
                    <p>Marque: {{ produit.marque }}</p>
                    <p>Modèle: {{ produit.modele }}</p>
                    <p>Puissance du son: {{ detailProduit.puissance }} Watts</p>
                    <p>Type d'alimentation: {{ detailProduit.alimentation }}</p>
                    <p>Couleur: {{ produit.couleur }}</p>
                <h3>Connectivité</h3>
                    <p>Wifi: {{ detailProduit.wifi }}</p>
                    <p>Bluetooth: {{ detailProduit.bluetooth }}</p>
                <h3>Dimension</h3>
                    <p>Hauteur: {{ produit.hauteur }} cm</p>
                    <p>Largeur: {{ produit.largeur }} cm</p>
                    <p>Profondeur: {{ produit.profondeur }} cm</p>
                    <p>Poid: {{ produit.poid }} g</p>
            </div>
            {% endfor %}
    {% endfor %}
{% endblock %}

File Rouge/Site/Regnaloub/templates/produit_detail/imprimante.html.twig
{% extends 'base_detail_produit.html.twig' %}

{% block caractéristique %}
    {% for produit in produit %}
        {% for detailProduit in detailProduit %}
            <div class="caracteristique_produit">
                <h2>Caractéristique du produit</h2>
                <h3>Caractéristiques générales</h3>
                    <p>Marque: {{ produit.marque }}</p>
                    <p>Modèle: {{ produit.modele }}</p>
                    <p>Type d'impression: {{ detailProduit.type }}</p>
                    <p>Format d'impression: {{ detailProduit.format }}</p>
                    <p>Vitesse d'impression: {{ detailProduit.vit }}</p>
                    <p>Qualite d'impression papier: {{ detailProduit.qualiter }}</p>
                    <p>Qualite d'impression photo: {{ detailProduit.qualiterPhoto }}</p>
                    <p>Couleur: {{ produit.couleur }}</p>
                <h3>Dimension</h3>
                    <p>Hauteur: {{ produit.hauteur }} cm</p>
                    <p>Largeur: {{ produit.largeur }} cm</p>
                    <p>Profondeur: {{ produit.profondeur }} cm</p>
                    <p>Poid: {{ produit.poid }} g</p>
            </div>
            {% endfor %}
    {% endfor %}
{% endblock %}

File Rouge/Site/Regnaloub/templates/produit_detail/ordinateur_portable.html.twig
{% extends 'base_detail_produit.html.twig' %}

{% block caractéristique %}
    {% for produit in produit %}
        {% for detailProduit in detailProduit %}
            <div class="caracteristique_produit">
                <h2>Caractéristique du produit</h2>
                <h3>Caractéristiques générales</h3>
                    <p>Marque: {{ produit.marque }}</p>
                    <p>Modèle: {{ produit.modele }}</p>
                    <p>Système d'exploitation: {{ detailProduit.sysExp }}</p>
                    <p>Processeur: {{ detailProduit.proc }}</p>
                    <p>Fréquence du processeur: {{ detailProduit.procFreq }}</p>
                    <p>Nombre de coeur: {{ detailProduit.procNbrCoeur }}</p>
                    <p>Modèle de la carte graphique: {{ detailProduit.cgModele }}</p>
                    <p>Stockage: {{ detailProduit.stkage }}Go</p>
                    <p>Type de stockage: {{ detailProduit.typeStkage }}</p>
                    <p>Webcam: {{ detailProduit.webcam }}</p>
                    <p>Couleur: {{ produit.couleur }}</p>
                <h3>Ecran</h3>
                    <p>Résolution de l'ecran: {{ detailProduit.resolution }} pixels</p>
                <h3>Connectivité</h3>
                    <p>Wifi: {{ detailProduit.wifi }}</p>
                    <p>Bluetooth: {{ detailProduit.bluetooth }}</p>
                <h3>Connectique</h3>
                    <p>Nombre de port USB: {{ detailProduit.portUsb }}</p>
                    <p>Nombre de port HDMI: {{ detailProduit.portHdmi }}</p>
                <h3>Mémoire</h3>
                    <p>Quantité de RAM: {{ detailProduit.ram }}Go</p>
                    <p>Fréquence RAM: {{ detailProduit.ramFreq }}MHz</p>
                <h3>Dimension</h3>
                    <p>Hauteur: {{ produit.hauteur }} cm</p>
                    <p>Largeur: {{ produit.largeur }} cm</p>
                    <p>Profondeur: {{ produit.profondeur }} cm</p>
                    <p>Poid: {{ produit.poid }} g</p>
            </div>
            {% endfor %}
    {% endfor %}
{% endblock %}

File Rouge/Site/Regnaloub/templates/produit_detail/telephone_tablette.html.twig
{% extends 'base_detail_produit.html.twig' %}

{% block caractéristique %}
    {% for produit in produit %}
        {% for detailProduit in detailProduit %}
            <div class="caracteristique_produit">
                <h2>Caractéristique du produit</h2>
                <h3>Caractéristiques générales</h3>
                    <p>Marque: {{ produit.marque }}</p>
                    <p>Modèle: {{ produit.modele }}</p>
                    <p>Système d'exploitation: {{ detailProduit.sysExp }}</p>
                    <p>Processeur: {{ detailProduit.procModele }}</p>
                    <p>Stockage: {{ detailProduit.memoire }}Go</p>
                    <p>Nombre de carte SIM: {{ detailProduit.nbrSim }}</p>
                    <p>Type de carte SIM: {{ detailProduit.typeSim }}</p>
                    <p>Couleur: {{ produit.couleur }}</p>
                <h3>Ecran</h3>
                    <p>Résolution de l'ecran: {{ detailProduit.resEcran }} pixels</p>
                    <p>Taille de l'ecran: {{ detailProduit.tailleEcran }}</p>
                    <p>Fréquence d'ecran: {{ detailProduit.freqEcran }}</p>
                <h3>Connectivité</h3>
                    <p>Reseaux: {{ detailProduit.reseau }}</p>
                    <p>Wifi: {{ detailProduit.wifi }}</p>
                    <p>Bluetooth: {{ detailProduit.bluetooth }}</p>
                <h3>Batterie</h3>
                    <p>Batterie: {{ detailProduit.bat }} mAh</p>
                    <p>État de la batterie: {{ detailProduit.etatBat }}</p>
                    <p>Type de chargement: {{ detailProduit.bluetooth }}</p>
                <h3>Mémoire</h3>
                    <p>Quantité de RAM: {{ detailProduit.ram }}Go</p>
                <h3>Dimension</h3>
                    <p>Hauteur: {{ produit.hauteur }} cm</p>
                    <p>Largeur: {{ produit.largeur }} cm</p>
                    <p>Profondeur: {{ produit.profondeur }} cm</p>
                    <p>Poid: {{ produit.poid }} g</p>
            </div>
            {% endfor %}
    {% endfor %}
{% endblock %}

File Rouge/Site/Regnaloub/templates/produit_detail/television.html.twig
{% extends 'base_detail_produit.html.twig' %}

{% block caractéristique %}
    {% for produit in produit %}
        {% for detailProduit in detailProduit %}
            <div class="caracteristique_produit">
                <h2>Caractéristique du produit</h2>
                <h3>Caractéristiques générales</h3>
                    <p>Marque: {{ produit.marque }}</p>
                    <p>Modèle: {{ produit.modele }}</p>
                    <p>Processeur: {{ detailProduit.proc }}</p>
                    <p>Puissance de son: {{ detailProduit.sonPuiss }} Watts</p>
                    <p>Couleur: {{ produit.couleur }}</p>
                <h3>Ecran</h3>
                    <p>Résolution de l'ecran: {{ detailProduit.resolution }} pixels</p>
                    <p>Définition de l'ecran: {{ detailProduit.def }}</p>
                    <p>Technologie: {{ detailProduit.techno }}</p>
                <h3>Connectique</h3>
                    <p>Nombre de port USB: {{ detailProduit.portUsb }}</p>
                    <p>Nombre de port HDMI: {{ detailProduit.portHdmi }}</p>
                <h3>Dimension</h3>
                    <p>Hauteur: {{ produit.hauteur }} cm</p>
                    <p>Largeur: {{ produit.largeur }} cm</p>
                    <p>Profondeur: {{ produit.profondeur }} cm</p>
                    <p>Poid: {{ produit.poid }} g</p>
            </div>
            {% endfor %}
    {% endfor %}
{% endblock %}

File Rouge/Site/Regnaloub/templates/produit_detail/unite_centrale.html.twig
{% extends 'base_detail_produit.html.twig' %}

{% block caractéristique %}
    {% for produit in produit %}
        {% for detailProduit in detailProduit %}
            <div class="caracteristique_produit">
                <h2>Caractéristique du produit</h2>
                <h3>Caractéristiques générales</h3>
                    <p>Marque: {{ produit.marque }}</p>
                    <p>Modèle: {{ produit.modele }}</p>
                    <p>Système d'exploitation: {{ detailProduit.sysExp }}</p>
                    <p>Processeur: {{ detailProduit.proc }}</p>
                    <p>Fréquence du processeur: {{ detailProduit.procFreq }}</p>
                    <p>Nombre de coeur: {{ detailProduit.procNbrCoeur }}</p>
                    <p>Modèle de la carte graphique: {{ detailProduit.cgModele }}</p>
                    <p>Stockage: {{ detailProduit.stkage }}Go</p>
                    <p>Type de stockage: {{ detailProduit.typeStkage }}</p>
                    <p>Couleur: {{ produit.couleur }}</p>
                <h3>Connectivité</h3>
                    <p>Wifi: {{ detailProduit.wifi }}</p>
                <h3>Connectique</h3>
                    <p>Nombre de port USB: {{ detailProduit.portUsb }}</p>
                    <p>Nombre de port HDMI: {{ detailProduit.portHdmi }}</p>
                <h3>Mémoire</h3>
                    <p>Quantité de RAM: {{ detailProduit.ram }}Go</p>
                    <p>Type de la RAM: {{ detailProduit.ramType }}</p>
                <h3>Dimension</h3>
                    <p>Hauteur: {{ produit.hauteur }} cm</p>
                    <p>Largeur: {{ produit.largeur }} cm</p>
                    <p>Profondeur: {{ produit.profondeur }} cm</p>
                    <p>Poid: {{ produit.poid }} g</p>
            </div>
            {% endfor %}
    {% endfor %}
{% endblock %}