File Rouge/Site/Regnaloub/src/Entity/Produit.php
<?php

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use App\Repository\ProduitRepository;
use ApiPlatform\Metadata\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
#[ApiResource]
#[ApiFilter(SearchFilter::class,
    properties: ["SousCategorie.id" => "exact"]
)]
class Produit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 30)]
    private ?string $ref = null;

    #[ORM\Column(length: 60)]
    private ?string $lib = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $Description = null;

    #[ORM\Column(length: 255)]
    private ?string $prix = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $prix_ht = null;

    #[ORM\Column(length: 50)]
    private ?string $marque = null;

    #[ORM\Column(length: 100)]
    private ?string $modele = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $hauteur = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $largeur = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $profondeur = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2)]
    private ?string $poid = null;

    #[ORM\Column]
    private ?int $sold = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?SousCategorie $SousCategorie = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Fournisseur $fournisseur = null;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Contient::class, orphanRemoval: true)]
    private Collection $produit;

    #[ORM\Column(length: 20)]
    private ?string $couleur = null;

    #[ORM\Column(length: 255)]
    private ?string $photo = null;

    #[ORM\Column(length: 255)]
    private ?string $slug = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?ConsoleGaming $consoleGaming = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?Enceinte $Enceinte = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?Imprimante $Imprimante = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?OrdinateurPortable $OrdinateurPortable = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?TelephoneTablette $TelephoneTablette = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?Television $Television = null;

    #[ORM\ManyToOne(inversedBy: 'produits')]
    private ?UniteCentral $UniteCentral = null;

    public function __construct()
    {
        $this->produit = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRef(): ?string
    {
        return $this->ref;
    }

    public function setRef(string $ref): static
    {
        $this->ref = $ref;

        return $this;
    }

    public function getLib(): ?string
    {
        return $this->lib;
    }

    public function setLib(string $lib): static
    {
        $this->lib = $lib;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): static
    {
        $this->Description = $Description;

        return $this;
    }

    public function getPrix(): ?string
    {
        return $this->prix;
    }

    public function setPrix(string $prix): static
    {
        $this->prix = $prix;

        return $this;
    }

    public function getPrixHt(): ?string
    {
        return $this->prix_ht;
    }

    public function setPrixHt(string $prix_ht): static
    {
        $this->prix_ht = $prix_ht;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(string $marque): static
    {
        $this->marque = $marque;

        return $this;
    }

    public function getModele(): ?string
    {
        return $this->modele;
    }

    public function setModele(string $modele): static
    {
        $this->modele = $modele;

        return $this;
    }

    public function getHauteur(): ?string
    {
        return $this->hauteur;
    }

    public function setHauteur(string $hauteur): static
    {
        $this->hauteur = $hauteur;

        return $this;
    }

    public function getLargeur(): ?string
    {
        return $this->largeur;
    }

    public function setLargeur(string $largeur): static
    {
        $this->largeur = $largeur;

        return $this;
    }

    public function getProfondeur(): ?string
    {
        return $this->profondeur;
    }

    public function setProfondeur(string $profondeur): static
    {
        $this->profondeur = $profondeur;

        return $this;
    }

    public function getPoid(): ?string
    {
        return $this->poid;
    }

    public function setPoid(string $poid): static
    {
        $this->poid = $poid;

        return $this;
    }

    public function getSold(): ?int
    {
        return $this->sold;
    }

    public function setSold(int $sold): static
    {
        $this->sold = $sold;

        return $this;
    }

    public function getSousCategorie(): ?sousCategorie
    {
        return $this->SousCategorie;
    }

    public function setSousCategorie(?sousCategorie $SousCategorie): static
    {
        $this->SousCategorie = $SousCategorie;

        return $this;
    }

    public function getFournisseur(): ?fournisseur
    {
        return $this->fournisseur;
    }

    public function setFournisseur(?fournisseur $fournisseur): static
    {
        $this->fournisseur = $fournisseur;

        return $this;
    }

    /**
     * @return Collection<int, Contient>
     */
    public function getProduit(): Collection
    {
        return $this->produit;
    }

    public function addProduit(Contient $produit): static
    {
        if (!$this->produit->contains($produit)) {
            $this->produit->add($produit);
            $produit->setProduit($this);
        }

        return $this;
    }

    public function removeProduit(Contient $produit): static
    {
        if ($this->produit->removeElement($produit)) {
            // set the owning side to null (unless already changed)
            if ($produit->getProduit() === $this) {
                $produit->setProduit(null);
            }
        }

        return $this;
    }

    public function getCouleur(): ?string
    {
        return $this->couleur;
    }

    public function setCouleur(string $couleur): static
    {
        $this->couleur = $couleur;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(string $photo): static
    {
        $this->photo = $photo;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getConsoleGaming(): ?ConsoleGaming
    {
        return $this->consoleGaming;
    }

    public function setConsoleGaming(?ConsoleGaming $consoleGaming): static
    {
        $this->consoleGaming = $consoleGaming;

        return $this;
    }

    public function getEnceinte(): ?Enceinte
    {
        return $this->Enceinte;
    }

    public function setEnceinte(?Enceinte $Enceinte): static
    {
        $this->Enceinte = $Enceinte;

        return $this;
    }

    public function getImprimante(): ?Imprimante
    {
        return $this->Imprimante;
    }

    public function setImprimante(?Imprimante $Imprimante): static
    {
        $this->Imprimante = $Imprimante;

        return $this;
    }

    public function getOrdinateurPortable(): ?OrdinateurPortable
    {
        return $this->OrdinateurPortable;
    }

    public function setOrdinateurPortable(?OrdinateurPortable $OrdinateurPortable): static
    {
        $this->OrdinateurPortable = $OrdinateurPortable;

        return $this;
    }

    public function getTelephoneTablette(): ?TelephoneTablette
    {
        return $this->TelephoneTablette;
    }

    public function setTelephoneTablette(?TelephoneTablette $TelephoneTablette): static
    {
        $this->TelephoneTablette = $TelephoneTablette;

        return $this;
    }

    public function getTelevision(): ?Television
    {
        return $this->Television;
    }

    public function setTelevision(?Television $Television): static
    {
        $this->Television = $Television;

        return $this;
    }

    public function getUniteCentral(): ?UniteCentral
    {
        return $this->UniteCentral;
    }

    public function setUniteCentral(?UniteCentral $UniteCentral): static
    {
        $this->UniteCentral = $UniteCentral;

        return $this;
    }

    public function __toString()
    {
        return $this->lib;
    }
    
}

File Rouge/Site/Regnaloub/src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

use App\Form\ContactFormType;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;

use App\Repository\CategorieRepository;
use App\Repository\ProduitRepository;
use App\Repository\SousCategorieRepository;

class MainController extends AbstractController
{
    #[Route('/', name: 'default')]
    public function index(ProduitRepository $prodRepo, CategorieRepository $cateRepo): Response
    {
        $produits = $prodRepo->findBy(array(), null, 10, null);
        $categories = $cateRepo->findBy(array(), null, 8, null);
        
        return $this->render('main/index.html.twig', [
            'produits' => $produits,
            'categories' => $categories,
        ]);
    }

    #[Route('/categorie', name: 'categorie')]
    public function categorie(CategorieRepository $cateRepo): Response
    {
        $categoriesPopu = $cateRepo->findBy(array(), null, 5, null);
        $categories = $cateRepo->findAll();
        
        return $this->render('main/categorie.html.twig', [
            'categories' => $categories,
            'categoriespopu' => $categoriesPopu,
        ]);
    }

    #[Route('/categorie/{categorie}', name: 'categorie_detail')]
    public function souscategorie($categorie, SousCategorieRepository $ScateRepo, CategorieRepository $cateRepo): Response
    {
        $sousCategorie = $ScateRepo->find($categorie);
        $categorie = $cateRepo->find($categorie);

        return $this->render('main/souscategorie.html.twig', [
            'sous_categorie' => $sousCategorie,
            'categorie' => $categorie,
        ]);
    }

    #[Route('/sous_categorie/{sCategorie}', name: 'sCategorie_detail')]
    public function sCateProduit($sCategorie, SousCategorieRepository $sCateRepo, ProduitRepository $prodRepo): Response
    {
        $sousCategorie = $sCateRepo->find($sCategorie);
        $produits = $prodRepo->findProduit($sCategorie);

        return $this->render('main/sCateProduit.html.twig', [
            'sousCategorie' => $sousCategorie,
            'produits' => $produits,
        ]);
    }

    #[Route('/produits', name: 'produit_all')]
    public function ProduitAll(ProduitRepository $prodRepo): Response
    {
        $produits = $prodRepo->findAll();

        return $this->render('main/produits.html.twig', [
            'produits' => $produits,
        ]);
    }

    #[Route('/contact', name: 'contact')]
    public function contact(Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ContactFormType::class);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()) {

            $data = $form->getData();

            $entityManager->persist($data);
            $entityManager->flush();

            return $this->redirectToRoute('default');
        }

        return $this->render('main/contact.html.twig', [
            'form' => $form,
        ]);
    }
}

File Rouge/Site/Regnaloub/templates/main/categorie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categorie{% endblock %}

{% block pub %} <div id="publicite">Publicité</div> {% endblock %}

{% block body %}
    <div id="categorie_all">
        <h1 id="categorie_titre_categorie">Catégories Populaires</h1>
        <div id="categorie">
            {% for categorie in categoriespopu %}
                <div class="card_categorie">
                    <a href="{{ path('categorie_detail', { categorie : categorie.id }) }}">
                        <img src="{{ categorie.photo }}" alt="">
                        <div class="card_categorie_lib_desc_btn">
                            <div class="card_categorie_lib_desc">
                                <p>{{ categorie.lib }}</p>
                                <p class="desc">{{ categorie.description|u.truncate(80, '...') }}</p>
                            </div>
                            <a class="btn_categorie" href="#">Visiter la categorie</a>
                        </div>
                    
                </div>
            {% endfor %}
        </div>

        <h1 id="categorie_titre_categorie">Toutes les catégories</h1>
        <div id="categorie">
            {% for categorie in categories %}
                <div class="card_categorie">
                    <a href="{{ path('categorie_detail', { categorie : categorie.id }) }}">
                        <img src="{{ categorie.photo }}" alt="">
                    <div class="card_categorie_lib_desc_btn">
                        <div class="card_categorie_lib_desc">
                            <p>{{ categorie.lib }}</p>
                            <p class="desc">{{ categorie.description|u.truncate(60, '...') }}</p>
                        </div>
                        <btn class="btn_categorie">Visiter la categorie</btn>
                    </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

File Rouge/Site/Regnaloub/templates/main/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}Contact{% endblock %}

{% block body %}
    <style>
    footer {
        position: absolute; 
        bottom: 0;
        left: 0;
        right: 0;
    }
    </style>

    <div id='contact'> 
        <h1 class="formH1">Prendre contact</h1>
        <div id="formContact">
            {{ form_start(form) }}
                <div id="formContactInputLabel">
                    {{ form_label(form.email, 'Adresse e-mail') }}
                    {{ form_widget(form.email, {'attr': {'class':'formInput75 contactInput'}}) }}
                    {{ form_errors(form.email, {'attr': {'class':'formContactErrors'}}) }}

                    {{ form_label(form.objet, 'Objet du message') }}
                    {{ form_widget(form.objet, {'attr': {'class':'formInput75 contactInput'}}) }}
                    {{ form_errors(form.objet, {'attr': {'class':'formContactErrors'}}) }}

                    {{ form_label(form.message, 'Votre message') }}
                    {{ form_widget(form.message, {'attr': {'class':'contactMessage'}}) }}
                    {{ form_errors(form.message, {'attr': {'class':'formContactErrors'}}) }}
                </div>

                <div id="formContactErrors">
                    {{ form_errors(form) }}
                </div>

                <div id="formContactBtn">
                    {{ form_row(form.envoyer, {'attr': {'class':'formBtn'}}) }}
                </div>

            {{ form_end(form) }}
        </div>
    </div>
{% endblock %}

File Rouge/Site/Regnaloub/templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block pub %} <div id="publicite">Publicité</div> {% endblock %}

{% block body %}
    <h1 id="accueil_titre_prod">Dernières sorties</h1>
    <div id="produit">
        {% for produit in produits %}
            <div class="card_produit">
                <a href="{{ path('produit_detail', { sCateLib: produit.SousCategorie.lib, produitSlug: produit.slug }) }}">
                    <img src="{{ asset('assets/img/produits/') ~ produit.photo }}" alt="photo catégorie">
                    <div class="card_produit_lib_desc_btn">
                        <div class="card_produit_lib_desc">
                            <p>{{ produit.lib }}</p>
                            {{ produit.description|u.truncate(80, '...')|raw }}
                            <div class="prix">
                                <p>{{ produit.prix }}€</p>
                                <p class="ht">{{ produit.prixht }}€HT</p>
                            </div>
                        </div>
                        <btn class="btn_panier">
                            Voir les details du produit
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
                            <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
                            </svg>
                        </btn>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>

    <div id="publicite">Publicité</div>

    <h1 id="accueil_titre_categorie">Nos différentes catégories</h1>
    <div id="accueil_categorie">
        {% for categorie in categories %}
            <div class="card_categorie">
                <a href="{{ path('categorie_detail', { categorie: categorie.id }) }}">
                    <img src="{{ categorie.photo }}" alt="">
                    <div class="card_categorie_lib_desc_btn">
                        <div class="card_categorie_lib_desc">
                            <p>{{ categorie.lib }}</p>
                        </div>
                        <btn class="btn_categorie" href="#">Visiter la categorie</btn>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    <h1 id="accueil_titre_propos">À propos</h1>
    <div id="accueil_propos">
        <div id="accueil_horraire">
            <h2>Horraire d'ouverture</h2>
            <div id="horraire" class="card_propos">
                <ul id="jours_horraires">
                    <ul id="jours">
                        <li>Lundi</li>
                        <li>Mardi</li>
                        <li>Mercredi</li>
                        <li>Jeudi</li>
                        <li>Vendredi</li>
                        <li>Samedi</li>
                        <li>Dimanche</li>
                    </ul>
                    <ul id="horraires">
                        <li>9h - 18h</li>
                        <li>9h - 18h</li>
                        <li>9h - 18h</li>
                        <li>9h - 18h</li>
                        <li>9h - 18h</li>
                        <li>9h - 18h</li>
                        <li>Fermé</li>
                    </ul>
                </ul>
            </div>
        </div>
        <div id="map" class="card_propos">
            <h2>Où nous trouver ?</h2>
            <img src="{{ asset('/assets/img/map.png') }}" alt="Map magasin">
        </div>
        <div id="accueil_contact_titre">
            <h2>Nous contacter</h2>
            <div id="contact_accueil" class="card_propos">
                <div id="mail_tel">
                    <div id="mail">
                        <p>Mail:</p>
                        <p>regnaloub@gmail.com</p>
                    </div>
                    <div id="telephone">
                        <p>Téléphone:</p>
                        <p>09.52.12.35.62</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

File Rouge/Site/Regnaloub/templates/main/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Panier{% endblock %}

{% block body %}
<div id="panier">
    <h1 id="panier_titre">Panier</h1>

    <div id="panier_all">
        {% set totalPanier = 0 %}
        {% set totalHtPanier = 0 %}
        {% set totalTVA = 0 %}

        <div class="panier_contenue_all">
            {% for item in panier %}

                {% set totalArticle = item.produit.prix * item.quantite %}
                {% set totalPanier = totalPanier + totalArticle %}

                {% set totalHtArticle = item.produit.prixHt * item.quantite %}
                {% set totalHtPanier = totalHtPanier + totalHtArticle %}

                {% set totalTVA = totalPanier - totalHtPanier %}

                <div class="panier_contenue">
                    <img src="{{ asset('assets/img/produits/') ~ item.produit.photo }}" alt="photo produit">
                    <div class="panier_lib_desc">
                        <h3>{{item.produit.lib}}</h3>
                        {{item.produit.description|u.truncate(300, '...')|raw}}
                    </div>

                    <div class="panier_quantiter_prix">
                        <div class="panier_quantite">
                            <div class="panier_ajouter_quantiter_retirer">
                                <a class="panier_ajouter" href="/add/{{item.produit.id}}">+</a>
                                <p>{{item.quantite}}
                                </p>
                                <a class="panier_retirer" href="/remove/{{item.produit.id}}">-</a>
                            </div>
                            <a class="a_trash" href="/delete/{{item.produit.id}}">
                                <svg class="icon_trash" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewbox="0 0 16 16">
                                    <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5m3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0z"/>
                                    <path d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4zM2.5 3h11V2h-11z"/>
                                </svg>
                            </a>
                        </div>

                        <div class="panier_prix_u">
                            <p>Total:</p>
                            <p class="panier_prix">{{ item.produit.prix * item.quantite }}€</p>
                            <p class="panier_prix_ht">{{ item.produit.prixHt * item.quantite }}€HT</p>
                        </div>
                    </div>
                </div>
            {% else %}
                <h2>Votre panier est vide</h2>
            {% endfor %}
        </div>

        <div class="panier_total">
            <ul>
                <li>Total Hors Taxe: <p>{{ totalHtPanier }}€ HT</p></li>
                <li>TVA: <p>{{ totalTVA }}€</p></li>
                <li class="total">Total: <p>{{ totalPanier }}€</p></li>
            </ul>
            <a href="#">Valider la commande</a>
        </div>
    </div>
</div>
{% endblock %}

File Rouge/Site/Regnaloub/templates/main/produits.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produits{% endblock %}

{% block pub %} <div id="publicite">Publicité</div> {% endblock %}

{% block body %}
    <h1 id="accueil_titre_prod">Liste de tout les produits</h1>
    <div id="produit">
        {% for produit in produits %}
            <div class="card_produit">
                <a href="{{ path('produit_detail', { sCateLib: produit.SousCategorie.lib, produitSlug: produit.slug }) }}">
                    <img src="{{ asset('assets/img/produits/') ~ produit.photo }}" alt="photo produit">
                    <div class="card_produit_lib_desc_btn">
                        <div class="card_produit_lib_desc">
                            <p>{{ produit.lib }}</p>
                            <p class="desc">{{ produit.description|u.truncate(60, '...') }}</p>
                            <div class="prix">
                                <p>{{ produit.prix }}€</p>
                                <p class="ht">{{ produit.prixht }}€HT</p>
                            </div>
                        </div>
                        <btn class="btn_panier">
                            Voir les details du produit
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
                            <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
                            </svg>
                        </btn>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

File Rouge/Site/Regnaloub/templates/main/sCateProduit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ sousCategorie.lib }} - Produits{% endblock %}

{% block pub %}{% endblock %}

{% block body %}
    <h1 id="accueil_titre_prod">{{ sousCategorie.lib }}</h1>
    <div id="produit">
        {% for produit in produits %}
            <div class="card_produit">
                <a href="{{ path('produit_detail', { sCateLib: produit.SousCategorie.lib, produitSlug: produit.slug }) }}">
                    <img src="{{ asset('assets/img/produits/') ~ produit.photo }}" alt="photo catégorie">
                    <div class="card_produit_lib_desc_btn">
                        <div class="card_produit_lib_desc">
                            <p>{{ produit.lib }}</p>
                            <p class="desc">{{ produit.description|u.truncate(80, '...') }}</p>
                            <div class="prix">
                                <p>{{ produit.prix }}€</p>
                                <p class="ht">{{ produit.prixht }}€HT</p>
                            </div>
                        </div>
                        <btn class="btn_panier" href="#">
                            Voir les details du produit
                            <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-caret-right-fill" viewBox="0 0 16 16">
                            <path d="m12.14 8.753-5.482 4.796c-.646.566-1.658.106-1.658-.753V3.204a1 1 0 0 1 1.659-.753l5.48 4.796a1 1 0 0 1 0 1.506z"/>
                            </svg>
                        </btn>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
{% endblock %}

File Rouge/Site/Regnaloub/templates/main/souscategorie.html.twig
{% extends 'base.html.twig' %}

{% block title %}Sous-Categorie{% endblock %}

{% block pub %}{% endblock %}

{% block body %}
    <div id="categorie_all">
        <h1 id="sCategorie_titre">{{ categorie.lib }}</h1>
        <p id="sCategorie_desc">{{ categorie.description }}</p>
        <div id="categorie">
            {% for souscate in categorie.sousCategories %}
                <div class="card_categorie">
                    <a href="{{ path('sCategorie_detail', { sCategorie: souscate.id }) }}">
                        <img src="{{ asset('assets/img/sCategories/') ~ souscate.photo }}" alt="">
                        <div class="card_categorie_lib_desc_btn">
                            <div class="card_categorie_lib_desc">
                                <p>{{ souscate.lib }}</p>
                                <p id="sCategorie_desc">{{ souscate.description|u.truncate(80, '...')  }}</p>
                            </div>
                            <btn class="btn_categorie">Visiter la sous categorie</btn>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

File Rouge/Site/Regnaloub/templates/main/validationPanier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Validation Panier{% endblock %}

{% block body %}
    <div id="confirmation_commande">
        <h1>Votre commande est bien enregistrée</h1>
        <h2>Un mail récapitulatif vous a été envoyé</h2>
        <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-check2-circle" viewBox="0 0 16 16">
            <path d="M2.5 8a5.5 5.5 0 0 1 8.25-4.764.5.5 0 0 0 .5-.866A6.5 6.5 0 1 0 14.5 8a.5.5 0 0 0-1 0 5.5 5.5 0 1 1-11 0"/>
            <path d="M15.354 3.354a.5.5 0 0 0-.708-.708L8 9.293 5.354 6.646a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0z"/>
        </svg>
    </div>
{% endblock %}